blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogpostCreateView, BlogpostListView, BlogpostDetailView, BlogpostUpdateView, BlogpostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create', BlogpostCreateView.as_view(), name='create'),
    path('', BlogpostListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogpostDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogpostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogpostDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
NULLABLE = {"null": True, "blank": True}


class Blogpost(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(unique=True, max_length=100, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blogpost/', verbose_name='изображение', **NULLABLE)
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'Публикация: {self.title}'

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = "публикации"
        ordering = ("-date_create",)

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blogpost


# Create your views here.

class BlogpostCreateView(CreateView):
    model = Blogpost
    fields = ('title', 'content', 'preview',)
    success_url = reverse_lazy('blog:list')

    extra_context = {
        'title': 'Создание публикации'
    }

    def form_valid(self, form):
        if form.is_valid():
            new_object = form.save()
            new_object.slug = slugify(new_object.title)

        return super().form_valid(form)


class BlogpostListView(ListView):
    model = Blogpost
    extra_context = {
        'title': 'Публикации'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogpostDetailView(DetailView):
    model = Blogpost
    extra_context = {
        'title': 'Публикация'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        return self.object


class BlogpostUpdateView(UpdateView):
    model = Blogpost
    fields = ('title', 'content', 'preview',)
    # success_url = reverse_lazy('blog:list')

    extra_context = {
        'title': 'Редакция публикации'
    }

    def form_valid(self, form):
        if form.is_valid():
            new_object = form.save()
            new_object.slug = slugify(new_object.title)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogpostDeleteView(DeleteView):
    model = Blogpost
    success_url = reverse_lazy('blog:list')

    extra_context = {
        'title': 'Удаление публикации'
    }

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="card mb-3" style="max-width: 100%;">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Вы действительно хотите удалить запись "{{ object.title }}" ?</p>
                        <button type="submit" class="btn btn-sm btn-outline-danger">Подтвердить</button>
                        <div class="btn-group">
                            <a href="{% url 'blog:view' object.pk %}" class="btn btn-sm btn-outline-primary">Назад</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'catalog/base.html' %}

{% load my_tags_blog %}
{% block content %}
<div class="card mb-3" style="max-width: 100%;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{% media_tag object.preview %}" class="img-fluid rounded-start" alt="Image">
    </div>
    <div class="col-md-8">

        <ol class="list-group list-group">
          <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
              <p class="card-text"><small class="text-body-secondary">Просмотры</small></p>
            </div>
            <span class="badge bg-primary rounded-pill">{{ object.views_count }}</span>
        </ol>

      <div class="card-body">
        <h4 class="card-title">{{ object.title }} ({{ object.slug }})</h4>
        <p class="card-text">{{ object.content }}</p>
        <p class="card-text"><small class="text-body-secondary">{{ object.date_create }}</small></p>

        <div class="btn-group">
          <a href="{% url 'blog:list' %}" class="btn btn-sm btn-outline-primary">Назад</a>
          <a href="{% url 'blog:edit' object.pk %}" class="btn btn-sm btn-outline-primary">Редактировать</a>
          <a href="{% url 'blog:delete' object.pk %}" class="btn btn-sm btn-outline-primary">Удалить</a>
        </div>


      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="card mb-3" style="max-width: 100%;">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit" class="btn btn-sm btn-outline-success">
                            {% if object %}
                                Сохранить изменения
                            {% else %}
                                Создать публикацию
                            {% endif %}
                        </button>
                        <div class="btn-group">
                            <a href="{% url 'blog:list' %}" class="btn btn-sm btn-outline-primary">Назад</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить запись</a>
</div>


<div class="list-group">
{% for object in object_list %}
  <a href="{% url 'blog:view' object.pk %}" class="list-group-item list-group-item-action">
      <div class="d-flex justify-content-end mt-auto">

          <ol class="list-group list-group">
              <li class="list-group-item d-flex justify-content-between align-items-start">
                  <div class="ms-2 me-auto">
                      <small class="text-body-secondary">Просмотры:</small>
                  </div>
                  <span class="badge bg-primary rounded-pill">{{ object.views_count }}</span>
          </ol>

      </div>
    <div class="d-flex w-100 justify-content-between">
      <h4 class="mb-1">{{ object.title | title }}</h4>
      <small class="text-body-secondary">{{ object.date_create }}</small>
    </div>
    <p class="mb-1">{{ object.content | truncatechars:111 }}</p>
    <small class="text-body-secondary">Добавил пользователь:</small>
  </a>
{% endfor %}
</div>

{% endblock %}