blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogpostCreateView, BlogpostListView, BlogpostDetailView, BlogpostUpdateView, BlogpostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create', BlogpostCreateView.as_view(), name='create'),
    path('', BlogpostListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogpostDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogpostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogpostDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, new_password_generate, VerificationCodeView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/new_pass_gen/', new_password_generate, name='new_pass_gen'),
    path('verification_code/', VerificationCodeView.as_view(), name='verification_code'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {
    'null': True,
    'blank': True,
}


# Create your models here.


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=50, verbose_name='номер телефона', **NULLABLE)
    country = models.CharField(max_length=100, verbose_name='страна', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)

    verification_code = models.CharField(max_length=100, verbose_name='проверочный код', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm

from users.models import User
from django import forms


class StyleFormMiXin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_active':
                field.widget.attrs['class'] = 'form-control'


class LoginViewForm(StyleFormMiXin, AuthenticationForm):

    class Meta:
        model = User
        fields = '__all__'


class UserRegisterForm(StyleFormMiXin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserForm(StyleFormMiXin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'country', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.contrib.auth.models import Group
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, LoginViewForm, UserForm
from users.models import User


# Create your views here.


class LoginView(BaseLoginView):
    model = User
    form_class = LoginViewForm
    template_name = 'users/login.html'
    extra_context = {
        'title': 'Вход пользователя'
    }


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:verification_code')
    template_name = 'users/register.html'
    extra_context = {
        'title': 'Регистрация пользователя'
    }

    def form_valid(self, form):
        password = User.objects.make_random_password()
        new_user = form.save(commit=False)
        new_user.verification_code = password
        new_user.save()
        send_mail(
            recipient_list=[new_user.email],
            subject='Регистрация на сайте Skystore',
            message=f'Введите код из для подтверждения регистрации: {new_user.verification_code}',
            from_email=settings.EMAIL_HOST_USER,
        )

        client_group = Group.objects.get(name='Клиент')
        client_group.user_set.add(new_user)

        return super().form_valid(form)


class VerificationCodeView(View):
    model = User
    template_name = 'users/verification_code.html'

    def get(self, request):
        return render(request, self.template_name)

    @staticmethod
    def post(request):
        verification_code = request.POST.get('verification_code')
        user = User.objects.filter(verification_code=verification_code).first()

        if user is not None and user.verification_code == verification_code:
            user.save()
            return redirect(reverse('users:login'))


class UserUpdateView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')
    extra_context = {
        'title': 'Редактирование профиля'
    }

    def get_object(self, queryset=None):
        return self.request.user


def new_password_generate(request):
    # new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    new_password = User.objects.make_random_password()

    send_mail(
        subject='Смена пароля вашего аккаунта',
        message=f'Ваш пароль изменен успешно на: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )

    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('catalog:index'))

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        {{ title }}
                    </h4>
                </div>
                <div class="card-body">
                    <form class="row" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit" class="btn btn-success">Войти</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        {{ title }}
                    </h4>
                </div>
                <div class="card-body">
                    <form class="row" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit" class="btn btn-success">Регистрация</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        {{ title }}
                    </h4>
                </div>
                <div class="card-body">
                    <form class="row" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit" class="btn btn-success">Сохранить изменения</button>
                    </form>
                </div>
                <div class="card-footer">
                    <a href="{% url 'users:new_pass_gen' %}" class="btn btn-danger">Сгенерировать новый пароль</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/verification_code.html
{% extends 'catalog/base.html' %}

{%block content%}

<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <div class="card">
            <div class="card-header">Верификация почты</div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input type="text" name="verification_code" class="form-control" id="verification_code"
                               placeholder="Введите код из письма"
                               required>
                        <input type="submit" class="btn btn-outline-primary mt-5" value="Отправить">
                    </div>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>

{% endblock %}