blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogpostCreateView, BlogpostListView, BlogpostDetailView, BlogpostUpdateView, BlogpostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create', BlogpostCreateView.as_view(), name='create'),
    path('', BlogpostListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogpostDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogpostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogpostDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductVersionUpdateView, \
    ProductDeleteView, CategoryListView, CategoryProductListView
from catalog.views import custom_permission_denied

app_name = CatalogConfig.name

urlpatterns = [
    path('contacts/', contacts, name='contacts'),
    path('', ProductListView.as_view(), name='index'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<int:category_id>/products/', CategoryProductListView.as_view(), name='category_products'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>', ProductVersionUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
    path('permission-denied/', custom_permission_denied, name='permission_denied'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.conf import settings
from django.db import models, connection
from django.http import HttpResponse
from django.shortcuts import get_object_or_404

NULLABLE = {"null": True, "blank": True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование категории')
    description = models.TextField(verbose_name='описание категории')

    @classmethod
    def truncate_table_restart_id(cls):
        with connection.cursor() as cursor:
            cursor.execute(f'TRUNCATE TABLE {cls._meta.db_table} RESTART IDENTITY CASCADE')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ("name",)


class Product(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец', **NULLABLE)
    name = models.CharField(max_length=100, verbose_name='наименование продукта')
    description = models.TextField(verbose_name='описание продукта')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')
    time_update = models.DateTimeField(auto_now=True, verbose_name='дата изменения')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ("name",)

    def can_edit(self, user):
        return self.owner == user


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.PositiveSmallIntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=150, verbose_name='название версии', **NULLABLE)
    is_active = models.BooleanField(verbose_name='активная версия', **NULLABLE)

    # переопределяем сейв метод для установки единственной is_active версии (*)
    def save(self, *args, **kwargs):
        if self.is_active:
            Version.objects.filter(product=self.product).exclude(pk=self.pk).update(is_active=False)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.version_number} - {self.version_name}: {self.is_active}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from catalog.models import Product, Version, Category


class StyleFormMiXin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_active' and field_name != 'is_published':
                field.widget.attrs['class'] = 'form-control'


def check_forbidden_words(value):
    forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    if value in forbidden_words:
        raise forms.ValidationError('введены недопустимые слова')

    return value


class ProductForm(StyleFormMiXin, forms.ModelForm):

    class Meta:
        model = Product
        # fields = '__all__'
        exclude = ('owner', 'is_published',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        return check_forbidden_words(cleaned_data)

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        return check_forbidden_words(cleaned_data)


class VersionForm(StyleFormMiXin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'


class ModeratorForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')


class CategoryForm(StyleFormMiXin, forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.forms import inlineformset_factory
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ModeratorForm, CategoryForm
from catalog.models import Product, Version, Category

from django.shortcuts import get_object_or_404

from catalog.services import get_cache_categories


# Create your views here.

class MyLoginRequiredMixin(LoginRequiredMixin):
    def handle_no_permission(self):
        return redirect(reverse('catalog:permission_denied'))


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    login_url = 'users:login'
    # template_name = 'catalog/product_list.html'
    extra_context = {
        'title': 'Товары нашего магазина'
    }

    def get_queryset(self):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return Product.objects.all()
        else:
            return Product.objects.filter(is_published=True)

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        products = Product.objects.all()
        active_versions = Version.objects.filter(is_active=True, product__in=products)
        context_data['active_versions'] = active_versions
        return context_data


def contacts(request):
    context = {
        'title': 'Наши контакты'
    }

    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Пользователь {name} ( номер телефона: {phone}) оставил сообщение: {message}')
    return render(request, 'catalog/contacts.html', context=context)


class ProductDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Product
    # template_name = 'catalog/product_detail.html'
    extra_context = {
        'title': 'Обзор товара'
    }
    permission_required = 'catalog.view_product'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        products = Product.objects.all()
        active_versions = Version.objects.filter(is_active=True, product__in=products)
        context_data['active_versions'] = active_versions
        return context_data


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')
    login_url = 'users:login'

    permission_required = 'catalog.add_product'

    extra_context = {
        'title': 'Добавление товара'
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductVersionUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    # form_class = ProductForm
    login_url = 'users:login'
    permission_required = 'catalog.change_product'

    extra_context = {
        'title': 'Изменение товара'
    }

    def get_form_class(self):
        if self.request.user.is_staff:
            return ModeratorForm
        else:
            return ProductForm

    def get_success_url(self):
        return reverse('catalog:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


def custom_permission_denied(request, pk=None):
    owner_email = "нет владельца"
    if pk:
        product = get_object_or_404(Product, pk=pk)
        owner_email = product.owner.email if product.owner else "нет владельца"
    context = {
        'title': 'Упс... что то пошло не так',
        'reason': 'Вы не зарегистрированы либо не являетесь владельцем этого товара.',
        'owner_email': owner_email
    }
    return render(request, 'catalog/permission_denied.html', context=context)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')
    extra_context = {
        'title': 'Удаление товара',
    }

    # def get(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     if not self.object.can_edit(request.user):
    #         return custom_permission_denied(request, pk=self.object.pk)
    #     return super().get(request, *args, **kwargs)


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    form_class = CategoryForm
    login_url = 'users:login'
    extra_context = {
        'title': 'Список категорий',
    }

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['object_list'] = get_cache_categories()

        return context_data


class CategoryProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalog/category_product_list.html'  # Замените на ваш шаблон
    context_object_name = 'product_list'

    def get_queryset(self):
        category = get_object_or_404(Category, id=self.kwargs['category_id'])
        return Product.objects.filter(category=category, is_published=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = get_object_or_404(Category, id=self.kwargs['category_id'])
        return context

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore: {{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_catalog_header.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - самый известный и крупный маркетплейс в России. Здесь можно заказать всё, что вам нужно!</p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}

{% include 'catalog/includes/inc_catalog_footer.html' %}
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}
<h1 class="display-4" style="text-align: center;">{{ title }}</h1>
<div class="container">

</div>
<div class="card mb-3" style="max-width: 100%;">
    {% for object in object_list %}
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{% media_tag object.image %}" class="img-fluid rounded-start" alt="Image">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h2 class="card-title">{{ object.name | title }}</h2>
                <p class="card-text">{{ object.description }}</p>
            </div>
        </div>
    </div>
    <footer class="text-muted">
        <div class="container">
            <div class="container mt-4 mb-4">
                {% if perms.catalog.add_product %}
                <a href="{% url 'catalog:product_create' %}" class="btn btn-primary">Добавить товар</a>
                {% endif %}
                <a href="{% url 'catalog:category_products' object.pk %}" class="btn btn-primary">Отобразить товары</a>
            </div>
        </div>
    </footer>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/category_product_list.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}
<h1 class="display-4" style="text-align: center;">{{ title }}</h1>
<div class="container">

</div>
<div class="card mb-3" style="max-width: 100%;">
    {% for object in object_list %}
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{% media_tag object.image %}" class="img-fluid rounded-start" alt="Image">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h2 class="card-title">{{ object.name }}</h2>
                <p class="card-text">{{ object.description }}</p>
            </div>
        </div>
    </div>
    <footer class="text-muted">
        <div class="container">
            <div class="container mt-4 mb-4">

                {% if object.owner == request.user or user.is_superuser or user.is_staff %}
                {% if perms.catalog.view_product %}
                <a href="{% url 'catalog:product' object.pk %}" class="btn btn-primary">Подробности</a>
                {% endif %}

                {% if perms.catalog.change_product %}
                <a href="{% url 'catalog:product_update' object.pk %}" class="btn btn-primary">Изменить товар</a>
                {% endif %}

                {% endif %}
            </div>
        </div>
    </footer>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{%block title%} {{ title }} {%endblock%}

{%block content%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <div class="row text-center">
                            <button type="submit" class="form-control btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}
<h1 class="display-4" style="text-align: center;">Товары</h1>
<div class="card mb-3" style="max-width: 100%;">
{% for object in object_list %}
  <div class="row g-0">
    <div class="col-md-4">
<!--      <img src="/media/{{ object.image }}" class="img-fluid rounded-start" alt="...">-->
<!--      <img src="{{ object.image | media_path }}" class="img-fluid rounded-start" alt="...">-->
      <img src="{% media_tag object.image %}" class="img-fluid rounded-start" alt="Image">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h2 class="card-title">{{ object.name | title }}</h2>
        <p class="card-text">{{ object.description | truncatechars:100 }}</p>

        <a href="{% url 'catalog:product' object.pk %}" class="btn btn-primary">подробности</a>
      </div>
    </div>
  </div>
{% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/permission_denied.html
{% extends 'catalog/base.html' %}

{% load my_tags %}
{%block title%} title {%endblock%}

{%block content%}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ reason }}</h1>
    <p class="lead">Адрес электронной почты владельца: {{ owner_email }}</p>
</div>


{%endblock%}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}

{% load my_tags %}
{%block title%} title {%endblock%}

{%block content%}
<div class="card mb-3" style="max-width: 100%;">
  <div class="row g-0">
    <div class="col-md-4">
<!--      <img src="/media/{{ object.image }}" class="img-fluid rounded-start" alt="...">-->
<!--      <img src="{{ object.image | media_path }}" class="img-fluid rounded-start" alt="...">-->
      <img src="{% media_tag object.image %}" class="img-fluid rounded-start" alt="Image">

    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h2 class="card-title">{{ object.name | title }}</h2>
        <p class="card-text">{{ object.description }}</p>
        <p class="card-text"><small class="text-body-secondary">дата публикации: {{ object.time_create }}</small></p>
        <h4 class="my-0 font-weight-normal">Цена {{ object.price }} руб.</h4><br>
        <a href="#" class="btn btn-primary">купить</a>
      </div>
    </div>
  </div>
</div>
{%endblock%}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                {% if object %}
                {{ title }}
                {% else %}
                {{ title }}
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Хотите удалить товар: {{ object.name }}</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                <a href="{% url 'catalog:index' %}" class="btn btn-primary">Отмена</a>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
{%endblock%}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% load my_tags %}
{%block title%} title {%endblock%}

{%block content%}
<div class="card mb-3" style="max-width: 100%;">
  <div class="row g-0">
    <div class="col-md-4">
<!--      <img src="/media/{{ object.image }}" class="img-fluid rounded-start" alt="...">-->
<!--      <img src="{{ object.image | media_path }}" class="img-fluid rounded-start" alt="...">-->
      <img src="{% media_tag object.image %}" class="img-fluid rounded-start" alt="Image">

    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h2 class="card-title">{{ object.name | title }}</h2>
        <p class="card-text">{{ object.description }}</p>
        <p class="card-text"><small class="text-body-secondary">дата публикации: {{ object.time_create }}</small></p>
        <p class="card-text"><small class="text-body-secondary">владелец: {{ object.owner|default:"нет владельца" }}</small></p>
        <h4 class="my-0 font-weight-normal">Цена {{ object.price }} руб.</h4><br>
        <a href="#" class="btn btn-primary">купить</a>
      </div>
    </div>
  </div>
</div>
<div>
<footer class="text-muted">
    <div class="container">
        <div class="container">
            {% if object.owner == request.user or user.is_superuser or user.is_staff %}
            {% if perms.catalog.delete_product %}
            <a href="{% url 'catalog:product_delete' object.pk %}" type="button" class="btn btn-danger">Удалить</a>
            {% endif %}
            {% if perms.catalog.change_product %}
            <a href="{% url 'catalog:product_update' object.pk %}" class="btn btn-primary">Изменить товар</a>
            {% endif %}
            <a href="{% url 'catalog:index' %}" class="btn btn-primary">Назад к списку</a>

            {% for version in active_versions %}
            {% if version.product_id == object.pk %}
            <p style="font-weight: bold; color: red;">Активная версия:
                {{ version.version_number }} - {{ version.version_name }}</p>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
</footer>
</div>
{%endblock%}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                {{ title }}
                {% else %}
                {{ title }}
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p}}
                <button type="submit" class="btn btn-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                <a href="{% url 'catalog:index' %}" class="btn btn-primary">Отмена</a>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
    {% if object %}
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {{ title }}
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}
<h1 class="display-4" style="text-align: center;">Товары</h1>
<div class="container">
    {% if perms.catalog.add_product %}
    <a href="{% url 'catalog:product_create' %}" class="btn btn-primary mb-5">Добавить товар</a>
    {% endif %}
</div>
<div class="card mb-3" style="max-width: 100%;">
    {% for object in object_list %}
    {% if object.is_published %}
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{% media_tag object.image %}" class="img-fluid rounded-start" alt="Image">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h2 class="card-title">{{ object.name | title }}</h2>
                <p class="card-text">{{ object.description | truncatechars:100 }}</p>
            </div>
        </div>
    </div>
    <footer class="text-muted">
        <div class="container">
            <div class="container mt-4 mb-4">

                {% if object.owner == request.user or user.is_superuser or user.is_staff %}
                {% if perms.catalog.view_product %}
                <a href="{% url 'catalog:product' object.pk %}" class="btn btn-primary">Подробности</a>
                {% endif %}

                {% if perms.catalog.change_product %}
                <a href="{% url 'catalog:product_update' object.pk %}" class="btn btn-primary">Изменить товар</a>
                {% endif %}

                {% for version in active_versions %}
                        {% if version.product_id == object.pk %}
                            <p style="font-weight: bold; color: red;">Активная версия:
                                {{ version.version_number }} - {{ version.version_name }}</p>
                        {% endif %}
                    {% endfor %}

                {% endif %}

            </div>
        </div>
    </footer>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}